#cloud-config
package_update: true
package_upgrade: true

packages:
  - nginx

users:
  - name: admin
    groups: sudo
    ssh_authorized_keys:
      - ${ssh_public_key}

runcmd:
  - mkdir -p /var/www/frontend.lucamaggio.xyz
  - cp -r /tmp/frontend-files/* /var/www/frontend.lucamaggio.xyz
  - chown -R www-data:www-data /var/www/frontend.lucamaggio.xyz
  - ln -sf /etc/nginx/sites-available/frontend.lucamaggio.xyz /etc/nginx/sites-enabled/
  - cp -r /tmp/frontend-files/* /var/www/default
  - chown -R www-data:www-data /var/www/default
  - ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
  - systemctl reload nginx

write_files:
  - path: /etc/nginx/sites-available/frontend.lucamaggio.xyz
    content: |
      server {
          listen 80; 
          server_name frontend.lucamaggio.xyz;
          root /var/www/frontend.lucamaggio.xyz;
          index index.html;
          location / {
              try_files $uri $uri/ =404;
          }
      }

  - path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80 default_server;
        server_name _;
        return 444;
      }

  - path: /tmp/frontend-files/index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Hello Terraform!</title>
      </head>
      <body>
          <h1>Deployed using Terraform on Hetzner!</h1>
      </body>
      </html>
