---
- name: Configure frontend server
  handlers:
    - name: Restart nginx
      listen: "reload nginx"
      ansible.builtin.service:
        name: nginx
        state: restarted
  hosts: frontend
  become: true
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Create website directories
      file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop:
        - /var/www/frontend.lucamaggio.xyz
        - /var/www/default

    - name: Create Nginx configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - src: "./conf/frontend.nginx.conf"
          dest: "/etc/nginx/sites-available"
        - src: "./conf/default.nginx.conf"
          dest: "/etc/nginx/sites-available"

    - name: Copy index page
      copy:
        src: "./conf/index.html"
        dest: "/var/www/frontend.lucamaggio.xyz"
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Enable Nginx site configurations
      file:
        src: "/etc/nginx/sites-available/{{ item }}"
        dest: "/etc/nginx/sites-enabled/{{ item }}"
        state: link
      loop:
        - default
        - frontend.nginx.conf
      notify: "reload nginx"
