---
- name: Configure frontend server
  handlers:
    - name: Restart nginx
      listen: "reload nginx"
      ansible.builtin.service:
        name: nginx
        state: restarted
  hosts: frontend
  become: true
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Create website directories
      file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop:
        - /var/www/{{ domain_name | default('example.com') }}
        - /var/www/default

    - name: Create Nginx configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - src: "./conf/{{ frontend_nginx_conf_filename }}"
          dest: "/etc/nginx/sites-available"
        - src: "./conf/default.nginx.conf"
          dest: "/etc/nginx/sites-available"
      notify: "reload nginx"

    - name: Copy index page
      copy:
        src: "./conf/{{ index_filename }}"
        dest: "/var/www/{{ domain_name | default('example.com') }}"
        owner: www-data
        group: www-data
        mode: '0755'
      notify: "reload nginx"

    - name: Delete default nginx conf
      file:
        dest: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: "reload nginx"

    - name: Enable Nginx site configurations
      file:
        src: "/etc/nginx/sites-available/{{ item }}"
        dest: "/etc/nginx/sites-enabled/{{ item }}"
        state: link
      loop:
        - default.nginx.conf
        - "{{ frontend_nginx_conf_filename }}"
      notify: "reload nginx"
