---
- name: Configure frontend server
  hosts: frontend
  become: true
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install nginx
      apt:
        name: nginx
        state: present
