---
- name: Configure frontend server
  hosts: frontend
  become: true
  tasks:
    - name: Update and upgrade packages
      apt:
        update_cache: true
        upgrade: true

    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Create website directories
      file:
        path: "{{ item }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
      loop:
        - /var/www/frontend.lucamaggio.xyz
        - /var/www/default
